[target.'cfg(target_os = "macos")']
rustflags = [
  "-C",
  "link-args=-Wl,-undefined,dynamic_lookup,-no_fixup_chains",
  "-C",
  "link-args=-all_load",
  "-C",
  "link-args=-weak_framework ScreenCaptureKit",
]

[target.'cfg(all(target_env = "gnu", not(target_os = "windows")))']
rustflags = ["-C", "link-args=-Wl,-z,nodelete"]
